Deep cleanup

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,9 +21,18 @@ jobs:
 
       - name: Build and push Docker image
         run: |
-          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mgmt_v2:latest
-          docker build --no-cache -t $IMAGE_NAME .
-          docker push $IMAGE_NAME
+              IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mgmt_v2
+              VERSION_TAG=${GITHUB_SHA::7}   # short commit hash (7 chars)
+
+              # Build with version and latest
+              docker build -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:latest .
+
+              # Push both tags
+              docker push $IMAGE_NAME:$VERSION_TAG
+              docker push $IMAGE_NAME:latest
+
+              echo "IMAGE_TAG=$VERSION_TAG" >> $GITHUB_ENV
+
 
       # Deploy to EC2
       - name: Deploy on EC2
@@ -42,14 +51,20 @@ jobs:
             docker stop mgmt_app || true
             docker rm mgmt_app || true
 
-             docker run --rm \
-            -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
-            -e ALLOWED_HOSTS="13.62.67.73" \
-            $IMAGE_NAME python manage.py migrate --fake
+            # Run migrations in a temporary container
+            docker run --rm \
+              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
+              -e DJANGO_ALLOWED_HOSTS="13.62.67.73,localhost" \
+              $IMAGE_NAME python manage.py migrate --noinput
 
             # Start new container
-            docker run -d -p 8000:8000 --name mgmt_app -e DJANGO_ALLOWED_HOSTS="13.62.67.73,localhost" $IMAGE_NAME
-            docker system prune -af --volumes || true  # cleanup unused layers
+            docker run -d -p 8000:8000 --name mgmt_app \
+              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
+              -e DJANGO_ALLOWED_HOSTS="13.62.67.73,localhost" \
+              $IMAGE_NAME
+
+              # Clean up unused images/layers
+              docker system prune -af --volumes || true
 
       - name: Send Email Notification
         uses: dawidd6/action-send-mail@v3
